# Generated by Django 4.2.2 on 2023-06-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('nombre2', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('apellido2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('comisaria', models.CharField(max_length=100, verbose_name='Comisaria')),
                ('cuadrante', models.IntegerField(verbose_name='Cuadrante')),
                ('telefCuadrante', models.IntegerField(verbose_name='Telefono Cuadrante')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('uniformidad', models.CharField(max_length=500)),
                ('aseo', models.CharField(max_length=500)),
                ('libro_novedades', models.CharField(max_length=500)),
                ('libro_asistencia', models.CharField(max_length=500)),
                ('turno', models.CharField(default='Diurno', max_length=20)),
                ('novedades', models.CharField(max_length=800)),
                ('id_instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporsuper.instalacion')),
                ('id_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporsuper.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporsuper.puesto'),
        ),
    ]
